In [1]:
import numpy as np

### Exercício 3

![google](representacao.png "Google")

Pesos de acordo com a Representação:

$$
\begin{cases} x_1 = x_8 / 2 \\ x_2 = x_1 / 2 \\ x_3 = x_1 / 2 + x_2 / 2 + x_8 / 2 \\ x_4 = x_2 / 2 \\ x_5 = x_4 / 2 \\ x_6 = x_3 / 2 + x_4 / 2 + x_5 / 1 \\ x_7 = x_3 / 2 + x_6 / 1 \\ x_8 = x_7 / 1 \end{cases} 
$$

### Criando a matriz A, conforme a representação anterior:

In [108]:
A = np.array([
    [.0, .0, .0, .0, .0, .0, .0, .5],
    [.5, .0, .0, .0, .0, .0, .0, .0],
    [.5, .5, .0, .0, .0, .0, .0, .5],
    [.0, .5, .0, .0, .0, .0, .0, .0],
    [.0, .0, .0, .5, .0, .0, .0, .0],
    [.0, .0, .5, .5, 1., .0, .0, .0],
    [.0, .0, .5, .0, .0, 1., .0, .0],
    [.0, .0, .0, .0, .0, .0, 1., .0]
])

In [109]:
A

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0.5, 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ]])

### Criando a matriz pertubada (Perron-Frobenius)

Valor do m, fizado no trabalho em 0.15

In [110]:
m_ = 0.15

Matriz S (n x n), com todas as entradas iguais a 1 / n:

In [111]:
x = np.ones((8, 8), dtype=float)
S = x * 1 / 8
S

array([[0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]])

Cáculo da matriz M:

In [112]:
M = ((1 - m_) * A) + (m_ * S)

In [113]:
for row in M:
    print(row)

[0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.44375]
[0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875]
[0.44375 0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.44375]
[0.01875 0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875]
[0.01875 0.01875 0.01875 0.44375 0.01875 0.01875 0.01875 0.01875]
[0.01875 0.01875 0.44375 0.44375 0.86875 0.01875 0.01875 0.01875]
[0.01875 0.01875 0.44375 0.01875 0.01875 0.86875 0.01875 0.01875]
[0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.86875 0.01875]


Verificando se a soma das colunas da matriz M é igual a 1:

In [114]:
np.sum(M, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

#### Obtendo: 
#### c = max 1≤j≤n | 1 − 2 min 1≤i≤n Mij |


In [130]:
c = np.max((1 - 2 * np.amin(M, axis=0)))

In [131]:
c

0.9625

#### Erro a posteriori:
#### || kx − x^(k) || ≤ c / (1 − c) * || x^k − x^(k-1) ||

In [157]:
def calculate_error(x_k_new, x_k_old):
    result = c / (1 -c) * np.sum(np.abs(x_k_new - x_k_old))
    
    return result
    

In [172]:
def calculate(X_, matriz_a, epslon=10e-5):
    
    cont = 1
    
    error = np.inf
    
    x_k_new = X_
    while True:
        # print(f'erro: {error}')
        
        x_k_old = x_k_new
        x_k_new = np.dot(matriz_a, x_k_old)

        error = calculate_error(x_k_new, x_k_old)
        
        if error < epslon:
            break
            
        cont += 1
        
    return cont, error, x_k_new

In [173]:
X_0 = np.array([
    1/8, 
    1/8,
    1/8,
    1/8,
    1/8,
    1/8,
    1/8,
    1/8
])

In [174]:
contador, error, matriz = calculate(X_0, M)

In [175]:
print(f'Foram realizadas {contador} iterações e o erro foi de {error}')

Foram realizadas 24 iterações e o erro foi de 6.41347701652746e-05


In [176]:
for row in matriz:
    print(row)

0.10564241611753487
0.06364823391396042
0.17759124170116974
0.045800591669674415
0.038215085398377376
0.14617428821693
0.2184747527797174
0.20445339020263512


In [180]:
print(f'As páginas exibidas por ordem de importância são: \n{matriz.argsort()[::-1] + 1}')

As paginas exibidas por ordem de importância são: 
[7 8 3 6 1 2 4 5]
