In [43]:
import numpy as np
import pandas as pd

### 5) Exemplo
#### Para testar o algoritmo, foi ealizado os cálculos com a matriz do item 5 exemplo do projeto.

In [2]:
consumo = np.array([[0.50, 0.40, 0.20],
                    [0.20, 0.30, 0.10],
                    [0.10, 0.10, 0.30]])

In [3]:
np.identity(consumo.shape[0]) - consumo

array([[ 0.5, -0.4, -0.2],
       [-0.2,  0.7, -0.1],
       [-0.1, -0.1,  0.7]])

In [4]:
input_table = np.array([[0.50, -0.40, -0.20],
                        [-0.20, 0.70, -0.10],
                        [-0.10, -0.10, 0.70]])

In [5]:
total_output = np.array([50, 30, 20])

In [6]:
resultado = np.sum(np.linalg.inv(input_table) * total_output, axis=1)

In [7]:
resultado

array([225.92592593, 118.51851852,  77.77777778])

### Tarefas

#### 2)

#### a)

Criando a matriz:

In [36]:
input_table = np.array([[.1588, .0064, .0025, .0304, .0014, .0083, .1594],
                        [.0057, .2645, .0436, .0099, .0083, .0201, .3413], 
                        [.0264, .1506, .3557, .0139, .0142, .0070, .0236],
                        [.3299, .0565, .0495, .3636, .0204, .0483, .0649],
                        [.0089, .0081, .0333, .0295, .3412, .0237, .0020],
                        [.1190, .0901, .0996, .1260, .1722, .2368, .3369],
                        [.0063, .0126, .0196, .0098, .0064, .0132, .0012]])

Subtraindo a identidade pela matriz:

In [37]:
input_table = np.identity(input_table.shape[0]) - input_table

In [38]:
input_table

array([[ 0.8412, -0.0064, -0.0025, -0.0304, -0.0014, -0.0083, -0.1594],
       [-0.0057,  0.7355, -0.0436, -0.0099, -0.0083, -0.0201, -0.3413],
       [-0.0264, -0.1506,  0.6443, -0.0139, -0.0142, -0.007 , -0.0236],
       [-0.3299, -0.0565, -0.0495,  0.6364, -0.0204, -0.0483, -0.0649],
       [-0.0089, -0.0081, -0.0333, -0.0295,  0.6588, -0.0237, -0.002 ],
       [-0.119 , -0.0901, -0.0996, -0.126 , -0.1722,  0.7632, -0.3369],
       [-0.0063, -0.0126, -0.0196, -0.0098, -0.0064, -0.0132,  0.9988]])

Calculando a sua inversa, ou seja, a matriz de Leontief:

In [39]:
np.linalg.inv(input_table)

array([[1.22119175, 0.02708562, 0.02256849, 0.06770014, 0.01354649,
        0.02265506, 0.21674832],
       [0.04324274, 1.40455448, 0.12438484, 0.04658356, 0.04036365,
        0.05162984, 0.51031329],
       [0.08055744, 0.33874893, 1.59274464, 0.0555055 , 0.05077394,
        0.03262524, 0.18095708],
       [0.67324352, 0.19045497, 0.17627673, 1.64480827, 0.09483497,
        0.12663949, 0.32647177],
       [0.0635781 , 0.05312934, 0.10097656, 0.08971729, 1.53927711,
        0.05751499, 0.05899924],
       [0.34094669, 0.27106498, 0.29527121, 0.32529467, 0.3841739 ,
        1.3673638 , 0.63713918],
       [0.02134809, 0.03032844, 0.03924566, 0.02311631, 0.0174619 ,
        0.02111642, 1.02455895]])

In [40]:
total_output = np.array([74000, 56000, 10500, 25000, 17500, 196000, 5000])

Obtendo o Resultado de X:

In [41]:
resultado = np.sum(np.linalg.inv(input_table) * total_output, axis=1)

In [42]:
resultado

array([ 99575.65339765,  97703.02286349,  51230.52316638, 131569.92192872,
        49488.49137236, 329554.45256999,  13835.33571501])

#### b)

In [14]:
input_table = np.array([[.1588, .0064, .0025, .0304, .0014, .0083, .1594],
                        [.0057, .2645, .0436, .0099, .0083, .0201, .3413],
                        [.0264, .1506, .3557, .0139, .0142, .0070, .0236],
                        [.3299, .0565, .0495, .3636, .0204, .0483, .0649],
                        [.0089, .0081, .0333, .0295, .3412, .0237, .0020],
                        [.1190, .0901, .0996, .1260, .1722, .2368, .3369],
                        [.0063, .0126, .0196, .0098, .0064, .0132, .0012]])

In [15]:
input_table = np.identity(input_table.shape[0]) - input_table

In [16]:
input_table

array([[ 0.8412, -0.0064, -0.0025, -0.0304, -0.0014, -0.0083, -0.1594],
       [-0.0057,  0.7355, -0.0436, -0.0099, -0.0083, -0.0201, -0.3413],
       [-0.0264, -0.1506,  0.6443, -0.0139, -0.0142, -0.007 , -0.0236],
       [-0.3299, -0.0565, -0.0495,  0.6364, -0.0204, -0.0483, -0.0649],
       [-0.0089, -0.0081, -0.0333, -0.0295,  0.6588, -0.0237, -0.002 ],
       [-0.119 , -0.0901, -0.0996, -0.126 , -0.1722,  0.7632, -0.3369],
       [-0.0063, -0.0126, -0.0196, -0.0098, -0.0064, -0.0132,  0.9988]])

In [ ]:
np.linalg.inv(input_table)

In [17]:
total_output = np.array([99640, 75548, 14444, 33501, 23527, 263985, 6526])

In [18]:
resultado = np.sum(np.linalg.inv(input_table) * total_output, axis=1)

In [19]:
resultado

array([134033.61532755, 131686.642968  ,  69471.69907937, 176912.002023  ,
        66595.55670623, 443772.90207667,  18431.17768329])

### 3)

#### Importando a tabela com os dados do IBGE:

In [52]:
df_table = pd.read_excel('ibge.xlsx')

In [53]:
df_table.head()

01\nAgropecuária  02\nIndústrias extrativas  \
0          0.040000                   0.000008   
1          0.000863                   0.054875   
2          0.211294                   0.112176   
3          0.023493                   0.010865   
4          0.000600                   0.012810   

   03\nIndústrias de transformação  \
0                         0.075729   
1                         0.042343   
2                         0.278665   
3                         0.015559   
4                         0.000907   

   04\nEletricidade e gás, água, esgoto e gestão de resíduos  05\nConstrução  \
0                                           0.000102                0.001096   
1                                           0.014855                0.009835   
2                                           0.077120                0.209774   
3                                           0.278018                0.001155   
4                                           0.013016                0.095640   

   06\nComércio  07\nTransporte, armazenagem e correio  \
0      0.008983                               0.000000   
1      0.000064                               0.000010   
2      0.056695                               0.186298   
3      0.017458                               0.005718   
4      0.000939                               0.003166   

   08\nInformação e comunicação  \
0                      0.000000   
1                      0.000000   
2                      0.026816   
3                      0.007179   
4                      0.016649   

   09\nAtividades financeiras, de seguros e serviços relacionados  \
0                                           0.000000                
1                                           0.000000                
2                                           0.008742                
3                                           0.004053                
4                                           0.002983                

   10\nAtividades imobiliárias  11\nOutras atividades de serviços  \
0                     0.000000                           0.004093   
1                     0.000582                           0.000043   
2                     0.009331                           0.071267   
3                     0.001247                           0.016636   
4                     0.002977                           0.003557   

   12\nAdministração, defesa, saúde e educação públicas e seguridade social  
0                                           0.001363                         
1                                           0.000061                         
2                                           0.025694                         
3                                           0.017357                         
4                                           0.014197

Convertendo os dados em Numpy Array:

In [54]:
input_table = np.array(df_table.values)

In [55]:
input_table

array([[3.99995822e-02, 7.67539231e-06, 7.57288057e-02, 1.01978381e-04,
        1.09598487e-03, 8.98286007e-03, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.09262654e-03, 1.36279826e-03],
       [8.62699225e-04, 5.48752173e-02, 4.23431276e-02, 1.48548508e-02,
        9.83539667e-03, 6.35922537e-05, 9.89282118e-06, 0.00000000e+00,
        0.00000000e+00, 5.82493328e-04, 4.28511670e-05, 6.12679654e-05],
       [2.11294467e-01, 1.12175859e-01, 2.78664919e-01, 7.71203778e-02,
        2.09774350e-01, 5.66952196e-02, 1.86297651e-01, 2.68157253e-02,
        8.74156603e-03, 9.33088369e-03, 7.12669322e-02, 2.56944600e-02],
       [2.34934096e-02, 1.08645178e-02, 1.55586610e-02, 2.78017788e-01,
        1.15450065e-03, 1.74578906e-02, 5.71805064e-03, 7.17901309e-03,
        4.05317684e-03, 1.24741496e-03, 1.66357753e-02, 1.73570490e-02],
       [5.99502851e-04, 1.28102298e-02, 9.07270409e-04, 1.30161497e-02,
        9.56400994e-02, 9.39348434e-04, 3.16570278e-03, 1.66

Subtraindo a matriz da sua identidade:

In [56]:
input_table = np.identity(input_table.shape[0]) - input_table

In [57]:
input_table

array([[ 9.60000418e-01, -7.67539231e-06, -7.57288057e-02,
        -1.01978381e-04, -1.09598487e-03, -8.98286007e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -4.09262654e-03, -1.36279826e-03],
       [-8.62699225e-04,  9.45124783e-01, -4.23431276e-02,
        -1.48548508e-02, -9.83539667e-03, -6.35922537e-05,
        -9.89282118e-06,  0.00000000e+00,  0.00000000e+00,
        -5.82493328e-04, -4.28511670e-05, -6.12679654e-05],
       [-2.11294467e-01, -1.12175859e-01,  7.21335081e-01,
        -7.71203778e-02, -2.09774350e-01, -5.66952196e-02,
        -1.86297651e-01, -2.68157253e-02, -8.74156603e-03,
        -9.33088369e-03, -7.12669322e-02, -2.56944600e-02],
       [-2.34934096e-02, -1.08645178e-02, -1.55586610e-02,
         7.21982212e-01, -1.15450065e-03, -1.74578906e-02,
        -5.71805064e-03, -7.17901309e-03, -4.05317684e-03,
        -1.24741496e-03, -1.66357753e-02, -1.73570490e-02],
       [-5.99502851e-04, -1.28102298e-02, -9.0727040

Calculando a Matriz de Leontief:

In [58]:
np.linalg.inv(input_table)

array([[1.07021867, 0.01967333, 0.11913949, 0.01649366, 0.03127004,
        0.02024246, 0.02757532, 0.00811978, 0.00431414, 0.00163785,
        0.01633623, 0.00750962],
       [0.01735771, 1.0691786 , 0.06755098, 0.0309118 , 0.02817317,
        0.00631082, 0.01541208, 0.00444266, 0.00225996, 0.00156184,
        0.00690959, 0.00377236],
       [0.3483731 , 0.23340532, 1.48826527, 0.19475651, 0.36504546,
        0.12594738, 0.33335425, 0.08606937, 0.04421615, 0.01903134,
        0.1395327 , 0.06776518],
       [0.04658876, 0.02821867, 0.04416328, 1.39503294, 0.01575094,
        0.03264903, 0.02267191, 0.02005962, 0.0123883 , 0.00311106,
        0.03209834, 0.02987718],
       [0.00271298, 0.01738047, 0.00468648, 0.02195886, 1.10766586,
        0.00322741, 0.00608135, 0.02283331, 0.00591383, 0.00371557,
        0.00652446, 0.01755871],
       [0.09294423, 0.06123864, 0.13065574, 0.05000287, 0.09621484,
        1.04539139, 0.0825488 , 0.04362592, 0.0168242 , 0.00595811,
        0.05048524,